python scripts/train_vit_features.py \
    --data-root data/raw/HPatches \
    --use-amp \
    --cudnn-benchmark \
    --compile \
    --epochs 100 \
    --pair-mode all_pairs \
    --batch-size 1 \
    --num-workers 8 \
    --lambda-det 1.0 \
    --lambda-desc 1.0 \
    --alpha-orient 0.32 \
    --resume checkpoints/best_model.pt \
    --use-synthetic-aug \
    --synthetic-ratio 0.5 \
